### ISSUE TITLE
Can't upgrade to Angular 9.1.X until version 8.0.0 is released. 

### ISSUE THREAD

**Issue by sorenfruergaard** [sneas/ionic-native-http-connection-backend#117]
### Subject of the issue
Can't upgrade to Angular 9.1.X until version 8.0.0 is released. 

### Environment
* version of angular - 9.1.X
* version of ionic-native-http-connection-backend - 7.0.3
* version of @ionic/angular
* version of @ionic-native/http - 5.22.0

### Steps to reproduce
Upgrading to Angular 9.1.4 fails when using version 7.0.3 of ionic-native-http-connection-backend. If I use version 8.0.0 the Angular upgrade works fine, so I would like to know when we can expect version 8.0.0 to become latest release?

**Comment by sneas** [comment]
Hi, this project's been using semantic releasing into different release channels of NPM. Everything that is committed to the master automatically goes to the `next` version. There is no particular strategy on moving a version from `next` to `latest` because this project is supported by a single person (me). I normally wait for the `next` version to be around for a bit (and tested by the library users) and then move `next` to `latest` eventually. The library is actually relying on users like you to use the `next` version and to report about any problems found or provide a PR fixing a problem.

There is no guarantee for the `latest` version to be flawless, as well as the `next` version to be buggy or unstable. So I would encourage you to start using the `next` version and report in case of any problem because this is the only way for this project to survive and receive necessary maintenance.

And a side note for myself: probably I have to reconsider release channels usage and get rid of the`next` release channel because it sometimes provides the wrong impression.

**Comment by sorenfruergaard** [comment]
Hi, thanks for the quick reply and thanks for explaining the release strategy.

We will start using version 8.0.0 and let you know if there are any issues.

I will close the issue.
