### ISSUE TITLE
How i change plugin options?

### ISSUE THREAD

**Issue by renanrider** [sneas/ionic-native-http-connection-backend#126]
### Subject of the issue
How i change plugin options? Ex cordova.plugin.http.setDataSerializer('urlencoded');
I have an form that use formdata, and i need change some options in ''cordova-plugin-advanced-http", but i dont have ideia how implement this.

### Environment
ionic/angular": "^5.0.0"
ionic-native-http-connection-backend": "^8.0.0"
ionic/angular 5.3.1
ionic-native/http": "^5.28.0"

### Actual behaviour
Don't works properly with default settings. The serve return status 599.

**Comment by sneas** [comment]
There is no way to set up serializer explicitly while performing a request with HttpClient. The serializer gets detected automatically based on request ([this function](https://github.com/sneas/ionic-native-http-connection-backend/blob/master/src/utils/detect-serializer-and-data.ts)).

The fact serializer is not detected automatically might be caused by a problem in the `detectSerializerAndData()` or elsewhere.

Can you provide a reproducible example? Feel free to fork this repo https://github.com/sneas/ionic-5-http-test.

**Comment by renanrider** [comment]
I made an example that has a similar error that I had in my application, the http error 599.
I don't know if the error is mine in the implementation. Thank you very much.

https://github.com/renanrider/ionic-test-http

**Comment by renanrider** [comment]
I updated the "ionic-native-http-connection-backend" plugin: "^ 8.1.1", and now the plugin calls the api. But I realized that my error is the same as the cases below, and not this plugin:

https://github.com/silkimen/cordova-plugin-advanced-http/issues/332
https://github.com/silkimen/cordova-plugin-advanced-http/issues/295
