### ISSUE TITLE
Support for Capacitor HTTP

### ISSUE THREAD

**Issue by digaus** [sneas/ionic-native-http-connection-backend#131]
### Subject of the issue

Would love to have an option for Capacitor HTTP https://github.com/capacitor-community/http instead of the cordova plugin.

Would this easily be possible or require a lot of work? An option to select which we want to use would be awesome.

**Comment by sneas** [comment]
Hi @digaus, thank you for referring me to `@capacitor-community/http`. As far as I see, the API of `@capacitor-community/http` differs from the API provided by `@ionic-native/http`. Since both plugins work in different environments and provide different APIs, I wouldn't go on including `@capacitor-community/http` into the current library. Having a standalone library/adaptor providing an Http backend working with `@capacitor-community/http` looks like a better option to me.

`ionic-native-http-connection-backend` was born as a necessity for a project I was working on three years ago. Since I don't work with Ionic anymore (might work someday in the future again, though), chances I'd have a necessity for a `@capacitor-community/http` <-> `@angular/common/http` adaptor are quite low, so I don't have any plans to work on `@capacitor-community/http` adaptor in the nearest future.

**Comment by digaus** [comment]
@sneas

Thanks for the reply. Imo Capacitor Http is the equivalent to Cordova Http (but still WIP). It uses a more robust bridge where you are very type safe and don't have to work so much with callbacks.

One can implement plugins more easily and safer. 

In current projects (Ionic App for iOS, Android, Electron and Web) we use Capacitor in combination with Cordova Http and this plugin. But for the future we would like to get rid of the Cordova plugins. For this it would be nice to just have another adapter.

Might have to do one myself then.

**Comment by sneas** [comment]
> Might have to do one myself then.

Good idea, mate! The world definitely needs this adapter.
