### ISSUE TITLE
img src handling

### ISSUE THREAD

**Issue by ghenry22** [sneas/ionic-native-http-connection-backend#19]
So I just added this to my ionic/cordova app and all looks great for standard http requests, but in my app I have a number of images loaded from the same remote site and all images still get caught by the "certificate is invalid" thing.

Is there any way to also hook or polyfill img src?

**Comment by sneas** [comment]
This is the security concern of WKWebView requests to https with self-signed certificate. The plugin solves only api requests by routing them through cordova plugin instead of browser's XHR.

In your particular case I may suggest using proxy server to the endpoint. You wouldn't need this plugin with the proxy.

I'll have a closer look at the problem. Probably there is another way.

**Comment by sneas** [comment]
Probably there is no solution to img src using the current plugin. Closing the issue.
