### ISSUE TITLE
Some Clarification On Usage

### ISSUE THREAD

**Issue by adamhodson** [sneas/ionic-native-http-connection-backend#50]
I know there are one or two closed issues in regards to usage but I'm still not 100% clear as I'm just tinkering with Ionic for the first time.

I'm currently importing the below in to my app

    import { HttpModule } from '@angular/http';
    import { HttpClientModule } from '@angular/common/http'; 

and importing both in to my app (@NgModule) 

In the example under HttpClientModule I see you're using 

    import { HttpBackend, HttpXhrBackend } from '@angular/common/http';

Is this meant to replace HttpClientModule? Or use in addition? I also see you are not importing anything other than NativeHttpModule in the example, so this should replace the HttpClientModule import all together?

**Comment by adamhodson** [comment]
Also here's my full app.module file if that helps

    import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';
import { IonicStorageModule } from '@ionic/storage';

import { HttpModule } from '@angular/http';
import { HttpClientModule } from '@angular/common/http'; 

//Pages
import { ProductListPage } from '../pages/product-list/product-list';
import { SingleProductPage } from '../pages/single-product/single-product';
import { CartPage } from '../pages/cart/cart';



//Providers
import { RestProvider } from '../providers/rest/rest';
// import { HttpNativeProvider } from '../providers/http-native/http-native';


@NgModule({
  declarations: [
    MyApp,
    HomePage,    
    ProductListPage,
    SingleProductPage,
    CartPage
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
    HttpModule,
    HttpClientModule,
    IonicStorageModule.forRoot()    
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage,    
    ProductListPage,
    SingleProductPage,
    CartPage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler},
    RestProvider  
  ]
})
export class AppModule {}

**Comment by sneas** [comment]
The library handles CORS issues on device only.

Consider this article https://blog.ionicframework.com/handling-cors-issues-in-ionic/ to handle CORS in browser when running the app with `ionic serve` or `ionic run`.

For successful CORS on device and in browser you need to apply 2 solutions simultaneously: this library on device and the article in browser.

You will be using different URLs on different environments. To make it transparently and simpler you may want to consider using Environment variables https://github.com/gshigeto/ionic-environment-variables.

I'm closing this issue because current discussion is getting far from the library's usage.

Feel free to reopen the issue concerning the usage of the library in context of iOS devices and specifically WKWebView.

**Comment by adamhodson** [comment]
Ah ok I better understand now. I actually started with that article you sent which worked for CORS but led to some other issues, so was thinking I might find a work around to those with your plugin. thanks for the assistance and resources.
