### ISSUE TITLE
Getting 415 - Unsupported Media Type when sending multipart/form-data request

### ISSUE THREAD

**Issue by e3mobiledev** [sneas/ionic-native-http-connection-backend#64]
Getting 415 error returned when request header has a contentType of "multipart/form-data"

Any fix or workaround?

Looks like this same issue was reported here last April: https://github.com/silkimen/cordova-plugin-advanced-http/issues/101

**Comment by sneas** [comment]
Hi @e3mobiledev,

Unfortunately it is not supported by both `cordova-plugin-advanced-http` and this library.

The only workaround I can suggest is to post good old JSON object instead of FormData object in case there are no files to be posted.

And to call [uploadFile](https://github.com/silkimen/cordova-plugin-advanced-http#uploadfile) directly on `cordova-plugin-advanced-http` in case some files must be uploaded.

Sorry for that.
