### ISSUE TITLE
Fallback not being used in web

### ISSUE THREAD

**Issue by willyboy** [sneas/ionic-native-http-connection-backend#70]
So I'm not sure if this is an issue or a feature request.

When I build my app with "ionic cordova build browser --prod" then the cordova http plugin is used because cordova is available:
https://github.com/sneas/ionic-native-http-connection-backend/blob/master/src/native-http-fallback.ts

This results in the "cookie not used on later requests" problem that was mentioned in another issue. It's a problem with the cordova http plugin itself.

It seems like if I'm on a desktop or mobile browser, then the fallback should always be used. 
Could you use a check of:
```
platform.is('core') || platform.is('mobileweb')
```
instead of 
```
checkAvailability('cordova.plugin.http')
```

If this makes sense, I can open a PR for it. If I'm missing something, let me know!

**Comment by sneas** [comment]
I wouldn't go that for for now implementing `platform.is('core') || platform.is('mobileweb')` because this is the first request of this kind. Need to make a research but smells like acting on platform detection should be out of concerns of this library. I might be wrong. Let's wait for other community members.

Since I can't guarantee the problem would be solved on library level in short time, for now I can suggest you to introduce your own fallback service into your project's code base:

```
providers: [
        {provide: HttpBackend, useClass: YourOwnFallBackClassWhichConsidersPlatformAndActsAccordingly, deps: [Platform, NativeHttpBackend, HttpXhrBackend]},
    ],
```

**Comment by sneas** [comment]
Closing for now.
