### ISSUE TITLE
Is there a way to enable logging?

### ISSUE THREAD

**Issue by shuppert** [sneas/ionic-native-http-connection-backend#89]
Is there a way to enable logging of requests when running on-device?  It's hard to debug issues on-device when you no longer see the network requests in an attached debugger.

-Scott

**Comment by sneas** [comment]
Giving the limited support resources it's out of the library's concerns for now. But you can introduce an HttpClientIntercptor covering your project's necessities.

Here is the example https://github.com/angular/angular/blob/master/aio/content/examples/http/src/app/http-interceptors/logging-interceptor.ts

**Comment by shuppert** [comment]
@sneas I added an HttpInterceptor as recommended but all I'm seeing is a generic 599 error:

HttpError: Error Code: 599
Message: Http failure response for (unknown url): 599 undefined

I see "599" in native-http-backend.ts.  Any ideas how to get more details on the isssue?

-Scott

**Comment by OsamaFelFel** [comment]
@shuppert how did you overcome that error?

**Comment by sneas** [comment]
@OsamaFelFel, Error Code 599 means `NETWORK CONNECT TIMEOUT ERROR`. It could be because of various reasons. Most likely related to the server or network.

You can try to refer to the `logging-interceptor` branch of [this repo](https://github.com/sneas/ionic-5-http-test/tree/logging-interceptor) to see the example of the login interceptor.

Places you'll have to refer to:

* [LogginInterceptor](https://github.com/sneas/ionic-5-http-test/blob/logging-interceptor/src/app/logging.interceptor.ts)
* [Intercetptor setup](https://github.com/sneas/ionic-5-http-test/blob/logging-interceptor/src/app/app.module.ts#L41)
* [HTTP request example](https://github.com/sneas/ionic-5-http-test/blob/logging-interceptor/src/app/tab1/tab1.page.ts#L12)
